### PR TITLE
FIX #48 - Added support for running nats-account-server as windows service

### LINKED ISSUE #48: Run nats-account-server as Windows Service
nats-account-server can currently not be run as a Windows Service. Starting a nats-account-server as Windows Service currently gives the following error: 
Windows could not start the MyNAS service on Local Computer.
Error 1053: The service did not respond to the start or control request in a timely fashion.

We believe this to be because "ServiceMain" is not implemented in this project.
There are workarounds for this like [nssm](https://nssm.cc/) but it would be prefered this is not needed. nats-server can currently already run as a windows service and it would be nice if nats-account-server could as well.

### PR DESCRIPTION
**Pull request by aricart**
- Added support so that nats-account-server can be installed with `sc` as a windows service
- Reworked the logger to reference the nats-server logger types rather than duplicate them
- Wired the system logger when running as a windows service

### CODE REVIEW

File: server/core/server.go [hunk 1]
```diff
@@ -74,18 +76,24 @@ type AccountServer struct {
...
 func NewAccountServer() *AccountServer {
-	return &AccountServer{
-		logger: logging.NewNATSLogger(logging.Config{
-			Colors: true,
-			Time:   true,
-			Debug:  true,
-			Trace:  true,
-		}),
+	ac := &AccountServer{
+		logger: NewNilLogger(),
```
Comment (kozlovic) [inline server/core/server.go]: That's all good to have a NilLogger for the tests, however having this here does not help. I have ran the tests locally and still can see logging. The reason is because the logger is set based on a given config (different than this one) in server.Start().

File: server/core/server.go [hunk 2]
```diff
@@ -74,18 +76,24 @@ type AccountServer struct {
...
+	}
+	return ac
+}
+
+func (server *AccountServer) ConfigureLogger() natsserver.Logger {
+	opts := server.config.Logging
+	if isWindowsService() {
```
Comment (kozlovic) [inline server/core/server.go]: Based on previous comment, we may want to have a server's config setting that "disables" logging, or allow to set a custom logger that would be set to the NilLogger.

File: server/core/server.go [hunk 3]
```diff
@@ -74,18 +76,24 @@ type AccountServer struct {
...
+		srvlogger.SetSyslogName("NatsAccountServer")
+		return srvlogger.NewSysLogger(opts.Debug, opts.Trace)
+	} else {
+		return srvlogger.NewStdLogger(opts.Time, opts.Debug, opts.Trace, opts.Colors, opts.PID)
```
Comment (kozlovic) [inline server/core/server.go]: Some linters will tell you that you should not have the `} else {` since previous `if` statement has a return.

**Comment by kozlovic** [comment]
@aricart I have updated the PR with some of the changes I commented on. A note regarding file watcher tests: the library being used seem really unreliable: we are getting unexpected number of notifications for the same file (especially on Windows).

**Comment by aricart** [comment]
@kozlovic The https://github.com/fsnotify/fsnotify library seems to be passing tests. The next question is whether that is needed. The server provides two kinds of stores, `nsc` and `dir` where it watches for modifications and performs a reload. Both of these are likely developer use cases, which I am not sure how required they are.

If the developer is using `nsc`, `nsc` already supports pushing the accounts to an account sever, so having it watch is not that useful. For the `dir` store where the jwts are immutable, I would argue, that is a simple http server that is read-only does that so long as the jwts are stored in the expected path. The normal `server` only writes if the jwts are signed by a trusted entity (ie , the operator for accounts and (need to verify it does this) accounts for tokens. Given that I am not sure why it would those two modes are useful. The normal mode would know when there's an update (http request), and would replicate the change.

Given the pairing of nsc to nats-account-server, I wouldn't be opposed to nsc writing a configuration for the account server that runs a live real server. That would be more useful in simulating the environment. NSC already generates static mem based configurations, so this is just the next step.

**Comment by aricart** [comment]
Going to open a different issue for the `nsc` and `dir` stores where we can continue the discussion.
